parser: '@typescript-eslint/parser'
env:
    browser: true
    es2021: true
    jest/globals: true
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/eslint-recommended'
    - 'plugin:@typescript-eslint/recommended'
parserOptions:
    ecmaVersion: 12
    sourceType: module
plugins:
    - prettier
    - '@typescript-eslint'
    - jest
rules: { 'prettier/prettier': 0 }
